# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: message.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'message.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rmessage.proto\"y\n\x08\x41\x64\x64Order\x12\x17\n\x0f\x63lient_order_id\x18\x01 \x01(\x03\x12\x13\n\x04side\x18\x02 \x01(\x0e\x32\x05.Side\x12\x1e\n\norder_type\x18\x03 \x01(\x0e\x32\n.OrderType\x12\r\n\x05price\x18\x04 \x01(\x03\x12\x10\n\x08quantity\x18\x05 \x01(\x03\"\x1f\n\x0b\x43\x61ncelOrder\x12\x10\n\x08order_id\x18\x01 \x01(\x03\"U\n\x0bModifyOrder\x12\x10\n\x08order_id\x18\x01 \x01(\x03\x12\x13\n\x04side\x18\x02 \x01(\x0e\x32\x05.Side\x12\r\n\x05price\x18\x03 \x01(\x03\x12\x10\n\x08quantity\x18\x04 \x01(\x03\"\x1f\n\x0bOrderAccept\x12\x10\n\x08order_id\x18\x01 \x01(\x03\"/\n\x0bOrderReject\x12\x10\n\x08order_id\x18\x01 \x01(\x03\x12\x0e\n\x06reason\x18\x02 \x01(\t\"T\n\x05Trade\x12\x14\n\x0c\x62id_order_id\x18\x01 \x01(\x03\x12\x14\n\x0c\x61sk_order_id\x18\x02 \x01(\x03\x12\r\n\x05price\x18\x03 \x01(\x03\x12\x10\n\x08quantity\x18\x04 \x01(\x03\" \n\x06Trades\x12\x16\n\x06trades\x18\x01 \x03(\x0b\x32\x06.Trade*\x8e\x01\n\x0bMessageType\x12\x1c\n\x18MESSAGE_TYPE_UNSPECIFIED\x10\x00\x12\r\n\tADD_ORDER\x10\x01\x12\x10\n\x0c\x43\x41NCEL_ORDER\x10\x02\x12\x10\n\x0cMODIFY_ORDER\x10\x03\x12\x10\n\x0cORDER_ACCEPT\x10\x04\x12\x10\n\x0cORDER_REJECT\x10\x05\x12\n\n\x06TRADES\x10\x06*/\n\x04Side\x12\x14\n\x10SIDE_UNSPECIFIED\x10\x00\x12\x07\n\x03\x42UY\x10\x01\x12\x08\n\x04SELL\x10\x02*W\n\tOrderType\x12\x1a\n\x16ORDER_TYPE_UNSPECIFIED\x10\x00\x12\x07\n\x03GTC\x10\x01\x12\x07\n\x03\x46\x41K\x10\x02\x12\x07\n\x03\x46OK\x10\x03\x12\n\n\x06MARKET\x10\x04\x12\x07\n\x03GFD\x10\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'message_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MESSAGETYPE']._serialized_start=463
  _globals['_MESSAGETYPE']._serialized_end=605
  _globals['_SIDE']._serialized_start=607
  _globals['_SIDE']._serialized_end=654
  _globals['_ORDERTYPE']._serialized_start=656
  _globals['_ORDERTYPE']._serialized_end=743
  _globals['_ADDORDER']._serialized_start=17
  _globals['_ADDORDER']._serialized_end=138
  _globals['_CANCELORDER']._serialized_start=140
  _globals['_CANCELORDER']._serialized_end=171
  _globals['_MODIFYORDER']._serialized_start=173
  _globals['_MODIFYORDER']._serialized_end=258
  _globals['_ORDERACCEPT']._serialized_start=260
  _globals['_ORDERACCEPT']._serialized_end=291
  _globals['_ORDERREJECT']._serialized_start=293
  _globals['_ORDERREJECT']._serialized_end=340
  _globals['_TRADE']._serialized_start=342
  _globals['_TRADE']._serialized_end=426
  _globals['_TRADES']._serialized_start=428
  _globals['_TRADES']._serialized_end=460
# @@protoc_insertion_point(module_scope)
