# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: risk_message.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'risk_message.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12risk_message.proto\"\x8f\x01\n\nCheckOrder\x12\x10\n\x08order_id\x18\x01 \x01(\x03\x12\x12\n\naccount_id\x18\x02 \x01(\t\x12\x0e\n\x06symbol\x18\x03 \x01(\t\x12\x17\n\x04side\x18\x04 \x01(\x0e\x32\t.RiskSide\x12\r\n\x05price\x18\x05 \x01(\x03\x12\x10\n\x08quantity\x18\x06 \x01(\x03\x12\x11\n\tis_market\x18\x07 \x01(\x08\"l\n\tApplyFill\x12\x10\n\x08order_id\x18\x01 \x01(\x03\x12\x12\n\naccount_id\x18\x02 \x01(\t\x12\x0e\n\x06symbol\x18\x03 \x01(\t\x12\x17\n\x04side\x18\x04 \x01(\x0e\x32\t.RiskSide\x12\x10\n\x08quantity\x18\x05 \x01(\x03\"?\n\x0cRiskDecision\x12\r\n\x05\x61llow\x18\x01 \x01(\x08\x12\x0e\n\x06reason\x18\x02 \x01(\t\x12\x10\n\x08order_id\x18\x03 \x01(\x03\"*\n\x0c\x41pplyFillAck\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\x0e\n\x06reason\x18\x02 \x01(\t*|\n\x0fRiskMessageType\x12!\n\x1dRISK_MESSAGE_TYPE_UNSPECIFIED\x10\x00\x12\x0f\n\x0b\x43HECK_ORDER\x10\x01\x12\x0e\n\nAPPLY_FILL\x10\x02\x12\x11\n\rRISK_DECISION\x10\x03\x12\x12\n\x0e\x41PPLY_FILL_ACK\x10\x04*B\n\x08RiskSide\x12\x19\n\x15RISK_SIDE_UNSPECIFIED\x10\x00\x12\x0c\n\x08RISK_BUY\x10\x01\x12\r\n\tRISK_SELL\x10\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'risk_message_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RISKMESSAGETYPE']._serialized_start=387
  _globals['_RISKMESSAGETYPE']._serialized_end=511
  _globals['_RISKSIDE']._serialized_start=513
  _globals['_RISKSIDE']._serialized_end=579
  _globals['_CHECKORDER']._serialized_start=23
  _globals['_CHECKORDER']._serialized_end=166
  _globals['_APPLYFILL']._serialized_start=168
  _globals['_APPLYFILL']._serialized_end=276
  _globals['_RISKDECISION']._serialized_start=278
  _globals['_RISKDECISION']._serialized_end=341
  _globals['_APPLYFILLACK']._serialized_start=343
  _globals['_APPLYFILLACK']._serialized_end=385
# @@protoc_insertion_point(module_scope)
